### ISSUE TITLE
Add installation, dependencies and compilation information to Readme

### ISSUE THREAD

**Issue by ghost** [TheBosZ/dartins#1]
i have been using a dart wrapper for electron, and this looks good for mobile.

can you add some notes to the readme about dependencies and compilation.
what things it expects to be on the os et.

i use osx.

**Comment by TheBosZ** [comment]
I'll update the readme with more notes.

Are you using the Cordova/Phonegap browser platform to target Electron?

**Comment by ghost** [comment]
thanks.

no i am not using Cordova to target Electron. Its not possible right ?

**Comment by ghost** [comment]
@TheBosZ  wow i did not even know you can use cordova to desktop apps now.

I will try it out for sure, because i need to and am using Electron at the moment.
Interesting ...

**Comment by TheBosZ** [comment]
This library is specifically for Cordova. Please report back on your experience! Thanks!

**Comment by ghost** [comment]
In the last 2 days i started using cordova to make OSX; windows, Ubuntu apps.
Also Android and IOS.
Its working well so far.

Now that i have confirmed that Cordova works on basically everything i will try your Dart package

Can you update the Readme with what you are Testing on / Supporting.
Thats way we can nail down what does and does not work per platform.

Good idea ?
